//! Generates the command reference from the clap definitions.
//!
//! CI regenerates this and fails if it differs from the committed
//! `docs/reference/commands.qmd`, so the reference cannot drift from the
//! binary: a command or flag that changes without the file being regenerated
//! breaks the build.

use minato::cli::Cli;

fn main() {
    let front_matter = r#"---
title: "Command reference"
subtitle: "Generated from the command-line definitions, so it never drifts from the binary."
---

<!-- Generated by `cargo run --example reference`; edit the clap definitions, not this file. -->

"#;

    print!("{front_matter}{}", clap_markdown::help_markdown::<Cli>());
}
